name: SEO Post-Deploy Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # every day 03:00 UTC
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  postdeploy-seo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NEXT_PUBLIC_SITE_URL: https://poj-pro.uz
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (npm ci)
        run: npm ci

      - name: Generate GSC URL list (with top products)
        run: npm run seo:gsc:urls

      - name: Upload URL list artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsc-submit-urls
          path: seo/gsc-submit-urls-*.txt
          if-no-files-found: error

      - name: Ping sitemaps (Google & Bing)
        run: npm run seo:sitemap:ping
